### ISSUE TITLE
install

### ISSUE THREAD

**Issue by plybb** [foyoux/aligo#10]
**新功能请求**

aligo根目录没有EXE也没有py文件，有没有办法在CMD中启动？

**Comment by lemisky** [comment]
小伙子，新手吧。这个是 Python的包，通过 pip安装，然后在Python中导入使用的，没有提供命令行相关工具和代码，当然你可以通过这个库封装一个

**Comment by plybb** [comment]
> 刚上大一，学了点皮毛。麻烦大神把“通过 pip安装，然后在Python中导入使用”开始这几步的具体操作写一下

> 小伙子，新手吧。这个是 Python的包，通过 pip安装，然后在Python中导入使用的，没有提供命令行相关工具和代码，当然你可以通过这个库封装一个

**Comment by lemisky** [comment]
晚点录个视频放这

**Comment by plybb** [comment]
> 晚点录个视频放这

非常期待。我翻到了aligo.mp4这个视频，它好像省略前面几步部署软件的操作，所以来求助

**Comment by lemisky** [comment]
https://user-images.githubusercontent.com/35125624/153203356-acfcbca7-6310-41d9-93ca-2c9753a59f0a.mp4

**Comment by advancejar** [comment]
你挂代理了？

**Comment by lemisky** [comment]
这个就是网络问题，自己检查下，不要开全局代理，尤其是使用anacoda时

**Comment by plybb** [comment]
> 你挂代理了？



> 这个就是网络问题，自己检查下，不要开全局代理，尤其是使用anacoda时

没错，一并回复二位。我所在的网络环境需要通过代理，才能连接互联网。我测试两种代理方式，一是在CMD中set proxy,另一种是用设置了http代理的git运行，以往这么做都没问题，这次就这样了。
