### ISSUE TITLE
自动签到怎么都返回none了？？

### ISSUE THREAD

**Issue by acoooder** [foyoux/aligo#107]
昨天开始自动签到貌似失效了，APP内手工签到后再脚本自动签可以正常返回，直接脚本自动签就是返回none

**Comment by lemisky** [comment]
收到

**Comment by wdisk2020** [comment]
是签到获得的延期卡 不能自动领了。是不要再来个请求啊 @lemisky

**Comment by lemisky** [comment]
现在好了

**Comment by lemisky** [comment]
已处理

**Comment by Ritchie1108** [comment]
好像还是不行, 看 sign_in_list 的返回结果
签到日期里的 isReward 字段是 false

**Comment by lemisky** [comment]
签到是可以了，但领取我不确定。

**Comment by Ritchie1108** [comment]
> 签到是可以了，但领取我不确定。

客户端里点击领取后, isReward 字段就是 true 了

**Comment by lemisky** [comment]
> 好像还是不行, 看 sign_in_list 的返回结果 签到日期里的 isReward 字段是 false

这个是这样的，你们帮忙看下签到是不是OK了。

**Comment by lemisky** [comment]
大家是想要 自动签到，同时也自动领取，对吗？

**Comment by Ritchie1108** [comment]
> 大家是想要 自动签到，同时也自动领取，对吗？

签到计数有正常加上去, 这个没问题
因为旧的流程是签到成功就会自动给奖励
现在是改成了签到成功, 手动领奖
所以会有点困惑, 希望还是和以前一样的认知, "签到成功=签到+领奖"

**Comment by lemisky** [comment]
好的，明白了，明天再看看，今天已经领过了，没法测试。这个功能我其实是不用的，需求和实际情况我是不了解的

**Comment by Ritchie1108** [comment]
不确定是不是这个action, 我也领了没法看😂
https://pages.aliyundrive.com/mobile-page/web/membershiporder.html?disableNav=YES&type=dailyCheck

**Comment by lemisky** [comment]
好的，谢谢😘

**Comment by acoooder** [comment]
> 好的，明白了，明天再看看，今天已经领过了，没法测试。这个功能我其实是不用的，需求和实际情况我是不了解的

非常感谢！实际情况是通过这个签到里的容量延期基本可以达到不购买容量一直试用8T容量的目的，但是基本要每天连续签才行，所以这个功能还是非常实用和必要的。

**Comment by wdisk2020** [comment]
就是原来的签到在20号左右 变成了2步 签到和领奖，之前是一步就完成了。

对于 白嫖阿里的空间 这个功能 非常有价值。 @lemisky  谢谢大佬抓包解决。我一会再试试

**Comment by wdisk2020** [comment]
sign_in_reward接口中
{'signInDay': 23} @lemisky  signInDay换成对应的天  就可以兑换了。刚测试过

**Comment by lemisky** [comment]
![ClapHandsApplauseGIF](https://user-images.githubusercontent.com/35125624/233889669-3e70b406-a78c-4285-aa3f-68de719ff70e.gif)

**Comment by lemisky** [comment]
已经更新示例，大家有问题再反馈哈

**Comment by acoooder** [comment]
> 已经更新示例，大家有问题再反馈哈

测试没有问题，点赞！！谢谢！~

**Comment by acoooder** [comment]
> sign_in_reward接口中 {'signInDay': 23} @lemisky signInDay换成对应的天 就可以兑换了。刚测试过

牛人！谢谢~~~

**Comment by wdisk2020** [comment]
sign_in_list  这个签到 奖品，好像和实际的不一样。本来打算没有奖就不领了。大佬看看哪个数据里 可以知道今天有没有奖。

**Comment by lemisky** [comment]
sign_in_list 这个接口返回的数据中有，你可以看看

**Comment by Ritchie1108** [comment]
> sign_in_list 这个签到 奖品，好像和实际的不一样。本来打算没有奖就不领了。大佬看看哪个数据里 可以知道今天有没有奖。

sign_in_list返回里,["result"]["sign_in_list"]是个数组, 找到对应的签到次数就是了

**Comment by wdisk2020** [comment]
sign_in_list25号没有卡，但APP里有

**Comment by Ritchie1108** [comment]
> sign_in_list25号没有卡，但APP里有

我这边正常, 注意调用顺序, 先 sign_in_list 在 sign_in_reward

**Comment by lemisky** [comment]
纳尼，有这等事情
![WhatNaniGIF](https://user-images.githubusercontent.com/35125624/234445051-8eb26824-8d92-4a6d-916a-b8080025fdc8.gif)

**Comment by wdisk2020** [comment]
> > sign_in_list25号没有卡，但APP里有
> 
> 我这边正常, 注意调用顺序, 先 sign_in_list 在 sign_in_reward, 还有就是 sign_in_list 的参数

我手机 看上去真的有卡 阿里不厚道啊

**Comment by Thesoul20** [comment]
现在的aligo 自动签到实现签到+领取功能了吗?

**Comment by lemisky** [comment]
> 现在的aligo 自动签到实现签到+领取功能了吗?

可以
