### ISSUE TITLE
download

### ISSUE THREAD

**Issue by plybb** [foyoux/aligo#11]
**新功能请求**

@lemisky 老师好，在你的帮助下，我已经成功登陆网盘，列出了文件目录。但是要从网盘中某个文件夹，找到一个文件，将其下载到本地指定目录，这个我看了源码注释还是不会。麻烦你再录一个视频，或者给代码和注释也可以。还有群号过期了，我想加。

**Comment by plybb** [comment]
会用了，多谢lemisky。下载速度好像跑不满，有开启多线程下载，或者调用aria2之类下载工具的方法吗
>  issue-11.mp4

**Comment by lemisky** [comment]
https://github.com/foyoux/aligo/blob/main/aligo/core/BaseAligo.py#L32-L32

**Comment by plybb** [comment]
> https://github.com/foyoux/aligo/blob/main/aligo/core/BaseAligo.py#L32-L32

你知道我的级别是看不懂的，专业知识有断层，无法把点连成片。再求一个视频，希望lemisky老师示范一下aria2c和IDM两种下载方式，我觉得之后我可以整理一个“新手入门教程”之类的东西贴出来。
