### ISSUE TITLE
运行例子“example-16 导出分享中所有文件信息.py”出错

### ISSUE THREAD

**Issue by gdjing** [foyoux/aligo#120]
**操作系统信息**

mac os big sur 11.1

**错误描述**

09:27:52.644 aligo.INFO Config /Users/xxx/.aligo/aligo.json
09:27:52.644 aligo.INFO 日志等级 DEBUG
09:27:52.644 aligo.INFO aligo 版本 6.0.4
09:27:52.644 aligo.INFO MacOS 操作系统
09:27:52.644 aligo.INFO 加载配置文件 /Users/chenxiaojing/.aligo/aligo.json
09:27:52.947 aligo.INFO POST https://api.aliyundrive.com/v2/share_link/get_share_token 200 560
Traceback (most recent call last):
  File "listallfile.py", line 36, in <module>
    main()
  File "listallfile.py", line 29, in main
    tree_share(share_id, share_token)
  File "listallfile.py", line 10, in tree_share
    file_list = ali.get_share_file_list(share_id, share_token, parent_file_id=parent_file_id)
TypeError: get_share_file_list() got multiple values for argument 'parent_file_id'

**Comment by lemisky** [comment]
旧例子没有修改

```py
file_list = ali.get_share_file_list(share_token, parent_file_id=parent_file_id)
```

**Comment by gdjing** [comment]
> 旧例子没有修改
> 
> ```python
> file_list = ali.get_share_file_list(share_token, parent_file_id=parent_file_id)
> ```

更新requests库并按照这个修改后正常了。谢谢！
