### ISSUE TITLE
直接下载别人分享的文件时出错

### ISSUE THREAD

**Issue by gdjing** [foyoux/aligo#122]
**操作系统信息**
WINDOWS 11
PYTHON 3.10

**错误描述**
获取分享中的jpg文件并下载，代码：
tree_share(share_id, share_token)
    #to_file()
    for file in all_files :
        #tmp = ali.get_share_link_download_url(file.file_id, share_token)
        ali.download_file(file_id = file.file_id,local_folder='.')

出错信息：
p1130375661.jpg, ID: 63b91f581df340992cd443a59833c1586da41670
126_front.jpg, ID: 63b91f586bd9760c22ba4fb38b03ee326666366f
126_back.jpg, ID: 63b91f5806d639b2a12746568f23e146b3f343cd
12:43:46.418 aligo.INFO POST https://api.aliyundrive.com/v2/file/get 404 86
12:43:46.419 aligo.WARNING 404 {"code":"NotFound.File","message":"The resource file cannot be found. file not exist"}
Traceback (most recent call last):
  File "E:\searchdownfile.py", line 46, in <module>
    main()
  File "E:\searchdownfile.py", line 37, in main
    ali.download_file(file_id = file.file_id,local_folder='.')
  File "C:\ProgramData\Python\lib\site-packages\aligo\apis\Download.py", line 168, in download_file
    return self._core_download_file(file_path, url)
  File "C:\ProgramData\Python\lib\site-packages\aligo\core\Download.py", line 51, in _core_download_file
    file_dir, file_name = os.path.split(os.path.abspath(file_path))
  File "C:\ProgramData\Python\lib\ntpath.py", line 566, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

**Comment by lemisky** [comment]
用下载链接，不能用 file_id，因为那不是你网盘中的文件

**Comment by gdjing** [comment]
> 用下载链接，不能用 file_id，因为那不是你网盘中的文件

谢谢大佬指导，如果用url下载，那“file_path”参数怎么来的？
我以为file有file_path属性，所以这样写：
```
tmp = ali.get_share_link_download_url(file.file_id, share_token)
ali.download_file(file_path= file.file_path, url=tmp.download_url)
```
还是报错：
```
16:12:13.670 aligo.INFO POST https://api.aliyundrive.com/v2/file/get_share_link_download_url 200 4794
Traceback (most recent call last):
  File "searchdownfile.py", line 46, in <module>
    main()
  File "searchdownfile.py", line 37, in main
    ali.download_file(file_path= file.file_path, url=tmp.download_url)
AttributeError: 'BaseShareFile' object has no attribute 'file_path'
```

**Comment by lemisky** [comment]
file path 是你你要下到哪里，即文件路径

**Comment by gdjing** [comment]
不是吧？我将file_path改成我想下载到的路径（"./"）后提示文件已存在：
```
tmp = ali.get_share_link_download_url(file.file_id, share_token)
        #print(ali.get_path(file.file_id,ali.get_drive))
        ali.download_file(file_path= './', url=tmp.download_url)
```

出错：

```
23:15:18.967 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list 200 410
23:15:19.113 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list 200 12210
在阿里云盘app购买8T会员怎样买最省钱？.jpg, ID: 648bfeeca189e34678a4483f8de72630c538d204
p1130375661.jpg, ID: 63b91f581df340992cd443a59833c1586da41670
126_front.jpg, ID: 63b91f586bd9760c22ba4fb38b03ee326666366f
126_back.jpg, ID: 63b91f5806d639b2a12746568f23e146b3f343cd
23:15:19.353 aligo.INFO POST https://api.aliyundrive.com/v2/file/get_share_link_download_url 200 4822
23:15:19.354 aligo.INFO 开始下载文件 /Users/xxx
23:15:19.354 aligo.WARNING 文件已存在,跳过下载 /Users/xxx
```

**Comment by lemisky** [comment]
完整的文件名，不是目录

**Comment by gdjing** [comment]
原来如此。。。运行通过了，感谢大佬指导！

**Comment by lemisky** [comment]
小事小事😜
