### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by yaoysyao** [foyoux/aligo#128]
**新功能请求**
1. 可以自定义登录成功后json配置文件的路径
2. 可以自定义登陆成功后是否生成json配置文件
。。。

**Comment by lemisky** [comment]
(如何自定义配置文件路径)[https://github.com/foyoux/aligo#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84]
