### ISSUE TITLE
当登陆过一次以后，再次使用是否还会重新登录

### ISSUE THREAD

**Issue by yaoysyao** [foyoux/aligo#129]
**新功能请求**
1. 当第一次登录时候，需要根据refresh_token进行登录，然后把所有的信息保存在配置文件中，使用代码是：
`ali = Aligo(refresh_token=refresh_token,re_login=False)`
如果登录成功以后在其他的文件中或者另一个程序中继续使用这个配置文件创建aligo，并且token还是有效的，那么需要重新登陆吗？
2. 如果配置文件已经存在，并且token是有效的，能否实现不重新登陆而是直接加载配置文件的access_token并且得到aligo进行后续的操作,如果配置文件存在，但是access_token已经失效此时在进行登录
以上在代码中有实现吗，如果有的话使用的时候需要设置参数吗，如果没有的话可以增加这个功能吗？
。。。

**Comment by yaoysyao** [comment]
每次调用这个ali = Aligo(refresh_token=refresh_token,re_login=False)都会执行登录吗，即便是已经登陆过了

**Comment by lemisky** [comment]
明天回复

**Comment by lemisky** [comment]
> 每次调用这个ali = Aligo(refresh_token=refresh_token,re_login=False)都会执行登录吗，即便是已经登陆过了

只要有 refresh_token 都会使用 refresh_token，如果已经了配置文件，会进行覆盖。re_login 参数的意思是， 当无法刷新 token 后，是否继续使用二维码登录

**Comment by lemisky** [comment]
> 

1. 不需要，但第一次运行成功后，之后不要传 refresh_token，refresh_token已经失效，正常的配置文件会被覆盖，总之 refresh_token 会被优先使用
2. 可以，就是不要传 refresh_token

**Comment by lemisky** [comment]
> **新功能请求**
> 
> 1. 当第一次登录时候，需要根据refresh_token进行登录，然后把所有的信息保存在配置文件中，使用代码是：
>    `ali = Aligo(refresh_token=refresh_token,re_login=False)`
>    如果登录成功以后在其他的文件中或者另一个程序中继续使用这个配置文件创建aligo，并且token还是有效的，那么需要重新登陆吗？
> 2. 如果配置文件已经存在，并且token是有效的，能否实现不重新登陆而是直接加载配置文件的access_token并且得到aligo进行后续的操作,如果配置文件存在，但是access_token已经失效此时在进行登录
>    以上在代码中有实现吗，如果有的话使用的时候需要设置参数吗，如果没有的话可以增加这个功能吗？
>    。。。


1. 不需要，但第一次运行成功后，之后不要传 refresh_token，refresh_token已经失效，正常的配置文件会被覆盖，总之 refresh_token 会被优先使用
2. 可以，就是不要传 refresh_token

**Comment by yaoysyao** [comment]
> > **新功能请求**
> > 
> > 1. 当第一次登录时候，需要根据refresh_token进行登录，然后把所有的信息保存在配置文件中，使用代码是：
> >    `ali = Aligo(refresh_token=refresh_token,re_login=False)`
> >    如果登录成功以后在其他的文件中或者另一个程序中继续使用这个配置文件创建aligo，并且token还是有效的，那么需要重新登陆吗？
> > 2. 如果配置文件已经存在，并且token是有效的，能否实现不重新登陆而是直接加载配置文件的access_token并且得到aligo进行后续的操作,如果配置文件存在，但是access_token已经失效此时在进行登录
> >    以上在代码中有实现吗，如果有的话使用的时候需要设置参数吗，如果没有的话可以增加这个功能吗？
> >    。。。
> 
> 1. 不需要，但第一次运行成功后，之后不要传 refresh_token，refresh_token已经失效，正常的配置文件会被覆盖，总之 refresh_token 会被优先使用
> 2. 可以，就是不要传 refresh_token

那如果我不传 refresh_token，并且设置re_login 为false,配置文件中的token也失效了，这个时候再次调用是会要求重新登陆还是直接抛出异常？

**Comment by lemisky** [comment]
抛出异常

![image](https://github.com/foyoux/aligo/assets/35125624/0e9cede5-6ba8-4471-b4d7-714036581750)

**Comment by yaoysyao** [comment]
> 抛出异常
> 
> ![image](https://user-images.githubusercontent.com/35125624/258745384-0e9cede5-6ba8-4471-b4d7-714036581750.png)

感谢

**Comment by yleafcc** [comment]
个人测试，使用refresh_token 获取access_token时的响应里面包含了新的refresh_token，如果使用新的refresh_token后续备用，目前没有遇到之前的1个月就过期的问题，但是Auth里面似乎没有针对新的refresh_token 做存储？

**Comment by yleafcc** [comment]
个人测试，使用refresh_token 获取access_token时的响应里面包含了新的refresh_token，如果每次都存储新的refresh_token后续使用，目前没有遇到之前的1个月就过期的问题，但是Auth里面似乎没有针对新的refresh_token 做存储？
