### ISSUE TITLE
登陆之后的配置文件能不能增加参数控制是否生成配置文件

### ISSUE THREAD

**Issue by yaoysyao** [foyoux/aligo#137]
登陆之后的配置文件能不能增加参数控制是否生成配置文件

**Comment by lemisky** [comment]
没太明白，这个需求的场景是什么

**Comment by yaoysyao** [comment]
> 没太明白，这个需求的场景是什么

如果我每次创建aligo实例的时候，是不是只要传入token就会每次都进行登录然后更新生成的配置文件，如果不给token的话会默认读取配置文件？

**Comment by lemisky** [comment]
对的
