### ISSUE TITLE
限速问题还有解决办法吗？

### ISSUE THREAD

**Issue by l-qiang** [foyoux/aligo#147]
使用api下载速度是**100kb/s**左右
api得到的直链通过IDM下载速度是**1mb/s**左右
阿里云客户端下载速度是**10mb/s**左右

**Comment by lemisky** [comment]
> api得到的直链通过IDM下载速度是1mb/s左右
>
> 阿里云客户端下载速度是10mb/s左右

我觉得应该不会呀

**Comment by l-qiang** [comment]
> > api得到的直链通过IDM下载速度是1mb/s左右
> > 阿里云客户端下载速度是10mb/s左右
> 
> 我觉得应该不会呀

昨天我试了很多次，确实是这样。
今天阿里云客户端的下载速度下来了，再加上我修改IDM的设置才保持持平2mb/s，阿里云盘客户端下载速度升高的时候我再试试看看。
是不是除了直链也没有其他方式下载了，得官方api？

**Comment by lemisky** [comment]
应该不会，我这里是能用 idm 满速 500mb

**Comment by l-qiang** [comment]
> 应该不会，我这里是能用 idm 满速 500mb

啊？？？？？？

**Comment by lemisky** [comment]
> > 应该不会，我这里是能用 idm 满速 500mb
> 
> 啊？？？？？？

对的，下几百G，几T，都是OK的

你可检查下， IDM 设置，比如有没有限速，几个线程，这些

**Comment by l-qiang** [comment]
> > > 应该不会，我这里是能用 idm 满速 500mb
> > 
> > 
> > 啊？？？？？？
> 
> 对的，下几百G，几T，都是OK的
> 
> 你可检查下， IDM 设置，比如有没有限速，几个线程，这些

我知道了，不是别得问题，是贫穷限制了我。我开了会员就可以满速了，带宽限制了我不能达到500mb
感谢你得答复

**Comment by l-qiang** [comment]
经过我的反复测试，限速问题依然明显，IDM开32线程可以超过非会员阿里云客户端，但是仍然无法满速。IDM偶尔也可以满速但是非常罕见。

**Comment by jadehh** [comment]
同样的问题,使用Alist获取Token可以达到满速度

**Comment by lemisky** [comment]
> 同样的问题,使用Alist获取Token可以达到满速度

这样的吗？可能用的 openapi，但不限速，有点不可思议，一般都是多线程实现速度提升的

目前 aligo 里可以调用 aria2c, 你可以试试
