### ISSUE TITLE
现在默认是备份盘，怎么查看资源库的文件呀

### ISSUE THREAD

**Issue by wkj89** [foyoux/aligo#151]
现在默认是备份盘，怎么查看资源库的文件呀

**Comment by lemisky** [comment]
老铁你不看说明的吗😅

https://github.com/foyoux/aligo?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E6%93%8D%E4%BD%9C%E8%B5%84%E6%BA%90%E7%9B%98
