### ISSUE TITLE
aria2c/IDM way of download

### ISSUE THREAD

**Issue by plybb** [foyoux/aligo#16]
希望@lemisky老师示范一下使用aria2c和IDM两种下载方式。

**Comment by lemisky** [comment]
idm 我查了下，没办法加 header, 有其他办法，那你肯定搞不来，跟你讲了也不明白

aria2c 的话：

```
aria2c <url> --referer=https://www.aliyundrive.com/
```

**Comment by plybb** [comment]
> aria2c <url> --referer=https://www.aliyundrive.com/
> 通过get_download_url得到了下载链接，并且添加了referer，使用aria2c下载出现错误提示authorization failed.

[
![error](https://user-images.githubusercontent.com/60730008/154879005-450b827b-3c19-4859-b7e7-1ab05bdfb8c5.jpg)
](url)

**Comment by lemisky** [comment]
你链接是不是搞错了呀

**Comment by plybb** [comment]
> 你链接是不是搞错了呀

aligo没有报错，aria2c是以往部署好平常在用。

**Comment by lemisky** [comment]
![image](https://user-images.githubusercontent.com/35125624/154948823-96172f37-0ffc-49ec-9958-147b41e2f701.png)

小伙子，你告诉我，这个链接地址是什么的？

你应该放文件的下载地址，知道吗，去检查下
