### ISSUE TITLE
share 相关的几个api中 x_share_token 好像需要转成字符串

### ISSUE THREAD

**Issue by aaron7970** [foyoux/aligo#160]
![image](https://github.com/foyoux/aligo/assets/157672353/e1117197-582d-4ec5-9256-75133c24393f)

![image](https://github.com/foyoux/aligo/assets/157672353/b6e7f014-e7e3-455f-93e8-7acab89d0bae)

![image](https://github.com/foyoux/aligo/assets/157672353/625332c6-e13e-4eea-b66c-461972da1f4d)

突然报错了，改成str就好了。 

_core_get_share_file_list
_core_batch_share_file_saveto_drive
_core_share_file_saveto_drive
_core_list_by_share

**Comment by lemisky** [comment]
能提供下 requests 版本吗

你尝试 重装 aligo 应该可以解决这个问题。

**Comment by aaron7970** [comment]
![image](https://github.com/foyoux/aligo/assets/157672353/4f4d8d9e-3754-4ab9-9c5d-0efb88dc451e)

嗯。 我在IDE里自动install的。  我改成了str()  就都可以了。
