### ISSUE TITLE
有个新需求，需要将账号绑定虚拟设备，这个可以做吗？

### ISSUE THREAD

**Issue by yaoysyao** [foyoux/aligo#162]
有个新需求，需要将账号绑定虚拟设备，将该设备在时光备份间中展示，并完成任务，这个有相应的接口吗？我看有些网站有这种功能，但是不知道咋做的

**Comment by lemisky** [comment]
虚拟设备不知道什么意思

接口应当有，aligo 没有全部实现，这个自己抓个包看看

这个我没用过，如果你可以提供流程（是什么东西？如何用？），接口我可以来实现

**Comment by yaoysyao** [comment]
> 虚拟设备不知道什么意思
> 
> 接口应当有，aligo 没有全部实现，这个自己抓个包看看
> 
> 这个我没用过，如果你可以提供流程（是什么东西？如何用？），接口我可以来实现

就是将阿里云盘绑定到设备上，但是这个设备不是真实的，而是随机生成的设备，主要的目的就是为了完成时光设备间的任务，时光设备间不是要求必须要在设备上登录，然后上传一个文件才可以领取奖励吗，但是有些设备不够5个，所以就想着能不能绑定随机生成的设备，然后使用这个设备的ID上传文件领取奖励

**Comment by lemisky** [comment]
实例化 Aligo 的不同 name 对象，就相当于一个对象

**Comment by yaoysyao** [comment]
> 实例化 Aligo 的不同 name 对象，就相当于一个对象

这样不行的，这样的话只是在账号管理那里的登录设备里面新增了一个登录设备，但是在时光备份间中还是同一个设备

**Comment by lemisky** [comment]
这样呀，那我就不清楚了😂
