### ISSUE TITLE
请问一下 list_by_share 这个接口，如果填写parent_file_id 是不是只在parent_file_id下遍历

### ISSUE THREAD

**Issue by aaron7970** [foyoux/aligo#165]
![image](https://github.com/foyoux/aligo/assets/157672353/e61cf3dc-a54e-440f-8912-2beb042240e8)

如果parent_file_id 不是root 是不是不会从root一直遍历到最后吧？ 阿里那边只会返回parent_file_id下的信息是吧？

**Comment by lemisky** [comment]
对
