### ISSUE TITLE
无法获取分享文件下载链接

### ISSUE THREAD

**Issue by LastNever** [foyoux/aligo#169]
![image](https://github.com/foyoux/aligo/assets/59238906/d1f9af4a-ed9a-4d75-a318-2862c968a4d9)
无法正确执行 ali.get_share_link_download_url（file_id, share_token）

**Comment by l-qiang** [comment]
我也有这个问题，刚来就看到这个issue

**Comment by LastNever** [comment]
`aligo.error.AligoFatalError: {"code":"ParamFlowException","message":"0ef0984511ad4320bf7bc476de28127f","requestId":"0a00801a17096001864604781ee431","resultCode":"ParamFlowException"}```

**Comment by LastNever** [comment]
`aligo.error.AligoFatalError: {"code":"ParamFlowException","message":"0ef0984511ad4320bf7bc476de28127f","requestId":"0a00801a17096001864604781ee431","resultCode":"ParamFlowException"}`

**Comment by lemisky** [comment]
我来看看

**Comment by lemisky** [comment]
我尝试了几下，均提示 429（这应该是官方接口小bug）

官方大概率下线了这个接口

已在库中做出标示，后续更新版本将删除

https://github.com/foyoux/aligo/releases/tag/v6.2.0

**Comment by l-qiang** [comment]
> 我也有这个问题，刚来就看到这个issue

改成先保存到自己网盘获取到下载链接后删除了，兄弟们有其他好的办法请务必告诉我
