### ISSUE TITLE
token 获取使用手机版获取

### ISSUE THREAD

**Issue by Kimiato** [foyoux/aligo#17]
**新功能请求**

目前版本使用的token为pc版本的token，获取下载链接下载时，需要带上 `"Referer": "https://www.aliyundrive.com/"` 的header，发现使用手机版本的token不需要，建议使用手机版登陆的token来获取下载链接。

**Comment by lemisky** [comment]
不确定这个特性是不是会一直存在，等我有空的时候看看吧。知道这个的时候，这个项目已经做完了，不然就搞它了

**Comment by Kimiato** [comment]
> 不确定这个特性是不是会一直存在，等我有空的时候看看吧。知道这个的时候，这个项目已经做完了，不然就搞它了

看到之前项目中有使用refresh_token的方式来操作，修改了下调用的代码，添加了一个可选参数 `use_refresh_token` ，使用后走的是通过手机端方式拿到的Authorization，这样download_url下载时不会校验 referer 的 header

请帮忙 review 下代码 💖

**Comment by lemisky** [comment]
来啦来啦
