### ISSUE TITLE
Feature Request: download_files add concurrency

### ISSUE THREAD

**Issue by hxzhao527** [foyoux/aligo#171]
just as the title says, add concurrency to method `download_files` to speed up downloading.

**Comment by lemisky** [comment]
不好意思才看到!

这个需求你用 download_url 自己实现吧😂

**Comment by hxzhao527** [comment]
也行吧.

顺路问个其他问题, 现在貌似被限速了. 即便使用的账户开启了会员. 是不是获取url过程有变化?

**Comment by lemisky** [comment]
至于为什么不加呢原因有很多，这不说。

客户端下载确实会有限速的现象，但目前为止使用 idm 下载，一直都是满速。

**Comment by lemisky** [comment]
应该不是获取链接的过程发生变化，可能针对某些账户做的限制，因为我自己用的比较少，每次用都还挺快，挺正常

**Comment by hxzhao527** [comment]
那我自己再查查, issue先关了
