### ISSUE TITLE
接口疑问

### ISSUE THREAD

**Issue by roiding** [foyoux/aligo#181]
aligo使用的接口是不是不是开放平台的接口地址？
举例：
二维码登陆的请求地址，aligo是/v2/oauth/authorize，但开发平台是 /oauth/authorize/qrcode
二维码状态，aligo是NEW、SCANED、CONFIRMED但接口文档却是WaitLogin、ScanSuccess、LoginSuccess、QRCodeExpired。

并且根据我对代码浅显的理解（未运行），没有任何进行refresh_token缓存的地方，那么aligo就不能适用于多次触发，只能在不关闭程序的情况下内存触发

**Comment by lemisky** [comment]
- 接口不是使用的开放平台
- 有保存 refresh_token， 在 Auth.py 文件中

**Comment by roiding** [comment]
auth中保存的refresh_token只存续在程序运行期间的内存中啊。

比如我想通过actions触发运行，第一次我扫二维码。后面触发我想通过第一次获取的refresh_token就没办法啊。

aligo还是只能存续在单次运行期间

**Comment by lemisky** [comment]
有持久化到硬盘

**Comment by roiding** [comment]
> 有持久化到硬盘

噢 终于看到了
默认名aligo的文件
ok 这样就可以搭配artifact来做多次操作了

所以作者你的api是直接扒的浏览器吧，哈哈哈

**Comment by lemisky** [comment]
登录持久化可以维持很久，可以到半年甚至更久。

差不多吧。如果官方喊停，我会马上删库跑路。😂

这个也是好久没搞了

**Comment by roiding** [comment]
咋说呢
我一直用的还是onedrive和oci
只支持oauth，没有sdk的阿里云有点蠢
话说国内貌似没哪个云盘支持oauth以外的认证方式，就很蠢
搞oauth，还得整localhost的服务器来支持回调
