### ISSUE TITLE
同步功能建议

### ISSUE THREAD

**Issue by zxc135781** [foyoux/aligo#19]
**新功能请求**

同步功能建议，能否增加只对比文件名选项，需要同步的文件都是很大且不会修改的文件，但是每次执行都要重新计算sha1，导致同步很慢，或可以缓存当前文件状态，无变化则跳过计算，希望采纳！

**Comment by lemisky** [comment]
增加只 对比 文件名，不关心内容有无变化，对吗？

**Comment by zxc135781** [comment]
> 增加只 对比 文件名，不关心内容有无变化，对吗？

是的

**Comment by lemisky** [comment]
OK

**Comment by lemisky** [comment]
@zxc135781 已更新，欢迎测试反馈

**Comment by zxc135781** [comment]
> @zxc135781 已更新，欢迎测试反馈

感谢！！

**Comment by lemisky** [comment]
上次加这个功能时，有点小问题，参数没有递归传递，现在已修复
