### ISSUE TITLE
pyw不能工作

### ISSUE THREAD

**Issue by ali88z** [foyoux/aligo#21]
**操作系统信息**

Win7

**错误描述**

以下内容以py后缀保存并运行，可以正常同步目录，但是如果以pyw保存则不行。需要添加类似Patch里的代码重定向输出才能工作，问题应该出在logging相关部分。

##### Patch 示意
            if sys.executable.endswith('pythonw.exe'):
                logger.warning('using pythonw.exe, redirect stdout to %s, stderr to %s', stdoutlog, stderrlog)
                sys.stdout = open(stdoutlog, 'w')
                sys.stderr = open(stderrlog, 'w')

##### 文件内容
import sys, logging
from aligo import Aligo

def aligo_test():
    local_folder2 = 'c:/Users/FZU/Desktop/c'
    # 云盘下的c目录，需要自己改成本人云上的某目录
    remote_folder_id = '622a6ffa09e4472cdf821198933437567fcab4cb'
    ali = Aligo(level = logging.DEBUG)
    ali.sync_folder(local_folder2, remote_folder_id)

def main():
    aligo_test()
    return 0

if __name__ == '__main__':
    sys.exit(main())

**Comment by lemisky** [comment]
经过考虑，这个问题和此库没有必然联系，patch 代码可以放在用户代码中。

感谢你的反馈🌹🌹
