### ISSUE TITLE
使用 pip 以及 pipenv 安装aligo失败，Python == 3.6.7

### ISSUE THREAD

**Issue by Thesoul20** [foyoux/aligo#30]
**操作系统信息**
Ubuntu 20.04
Python版本为 3.6.7
pip版本 21.3.1
pipenv版本 2022.1.8

**错误描述**
在使用pipenv以及pip安装aligo时会出现 Could not find a version 的错误。
```bash
> pip install aligo
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement aligo (from versions: none)
ERROR: No matching distribution found for aligo
```
但是在 [https://pypi.tuna.tsinghua.edu.cn/simple/](https://pypi.tuna.tsinghua.edu.cn/simple/) 网站上能够检索到aligo库。
同时，当使用pipenv 进行安装的时候也会出现同样的错误：
```bash
> pipenv install aligo --skip-lock
Installing aligo...
Error:  An error occurred while installing aligo!
Error text: Looking in indexes: https://mirrors.aliyun.com/pypi/simple/

ERROR: Could not find a version that satisfies the requirement aligo (from versions: none)
ERROR: No matching distribution found for aligo

✘ Installation Failed 
```
同样的，也能够在[https://mirrors.aliyun.com/pypi/simple/](https://mirrors.aliyun.com/pypi/simple/ )上检索到aligo的信息。
这该如何解决呢？

**Comment by lemisky** [comment]
不支持 Python 3.6，3.7 起。

解决方案：升级python
