### ISSUE TITLE
后面是否会支持java版SDK

### ISSUE THREAD

**Issue by akwangl** [foyoux/aligo#34]

**Comment by lemisky** [comment]
不会哦

**Comment by akwangl** [comment]
那我还是老老实实用py吧
api文档写的很用心


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foyoux/aligo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 晚上10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foyoux/aligo] 后面是否会支持java版SDK (Issue #34)





 
不会哦

**Comment by lemisky** [comment]
🤣
