### ISSUE TITLE
有些文件有时候会403

### ISSUE THREAD

**Issue by akwangl** [foyoux/aligo#35]
**错误描述**
当我使用file.download_url字段去用postman下载时会403但有时候又可以成功，作者有遇到类似的情况吗
。。。

**Comment by akwangl** [comment]
![image](https://user-images.githubusercontent.com/39325175/181435813-f46d607d-3573-4f96-a253-7a8e9b896788.png)

**Comment by akwangl** [comment]
必须得加这个吗？我不知道这个到底有什么用但是它可以让下载成功

**Comment by lemisky** [comment]
晚上咱讨论下，你加群然后加我

**Comment by akwangl** [comment]
你群号是多少，二维码过期了

**Comment by lemisky** [comment]
> 



> 必须得加这个吗？我不知道这个到底有什么用但是它可以让下载成功

看情况

防盗链的

**Comment by lemisky** [comment]
二维码有更新

**Comment by akwangl** [comment]
好的
