### ISSUE TITLE
启动错误-卡在加载配置文件

### ISSUE THREAD

**Issue by Biubush** [foyoux/aligo#39]
**操作系统信息**
linux环境和windows环境都已测试
linux测试环境:Debian
windows测试环境:win10

**错误描述**
![错误描述](https://user-images.githubusercontent.com/15962307/184413922-6b5a7994-b52b-4f63-a948-d7db1e931910.png)
一直卡在以上页面，删除配置文件后重启，问题仍然存在

**Comment by lemisky** [comment]
明晚处理

**Comment by lemisky** [comment]
无法复现你说的问题
