### ISSUE TITLE
「TypeError: __init__() got an unexpected keyword argument 'domain_id'」错误

### ISSUE THREAD

**Issue by lhanlhanlhan** [foyoux/aligo#4]
情况描述：
1. 之前已成功登录过1次，登录信息已被保存至 aligo.json，且登录后所有功能都可正常调用。
2. 上次成功登录1天后，重新打开 Python，重新使用 ali = Aligo() 创建对象，并尝试调用上传文件接口，出现「TypeError: __init__() got an unexpected keyword argument 'domain_id'」错误，无法上传。
3. 上述问题怀疑是登录态没有自动更新导致，遂删除「aligo.json」文件，然后重新使用 auth = Auth() 创建对象，打算重新扫描二维码、重新登录。
4. 在重新扫描二维码登录后，又出现「TypeError: __init__() got an unexpected keyword argument 'domain_id'」错误，而 auth 对象并未成功创建，无法使用任何功能。

附：重新扫描二维码登录后，打印出来的 Log 如下

23:37:22.128  INFO 等待扫描二维码 ...
23:37:22.129  INFO 已扫描, 等待确认 ...
23:37:24.270  INFO 等待扫描二维码 ...
23:37:24.270  INFO 已确认 (你可以关闭二维码图像了.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/han/miniconda3/lib/python3.8/site-packages/aligo/core/Auth.py", line 154, in __init__
    self._login()
  File "/home/han/miniconda3/lib/python3.8/site-packages/aligo/core/Auth.py", line 200, in _login
    self.token = Token(**response.json())
TypeError: __init__() got an unexpected keyword argument 'domain_id'

跪请大佬协助解决问题！

**Comment by advancejar** [comment]
更新版本,已解决

**Comment by lemisky** [comment]
> 更新版本,已解决

正解@advancejar

**Comment by lemisky** [comment]
昨天邮件看漏了，现在才发现
