### ISSUE TITLE
将其他分享转存到我的网盘功能

### ISSUE THREAD

**Issue by chenlip** [foyoux/aligo#40]
**新功能请求**

将其他分享转存到我的网盘功能

**Comment by chenlip** [comment]
# 5.现在我们可以进行保存了, 比如我们保存到网盘根目录, 此时 to_parent_file_id 可以省略
save_file = ali.share_file_saveto_drive(share_id, file_id=share_file_list[0].file_id, share_token=share_token.share_token, to_parent_file_id='root')


报错:  {"code":"ForbiddenNoPermission.File","message":"No Permission to access resource File"}

**Comment by chenlip** [comment]
我是对一个公开的分享(没有密码) 进行保存时; 
报错{"code":"ForbiddenNoPermission.File","message":"No Permission to access resource File"}

**Comment by lemisky** [comment]
是可以保存的，share_token=share_token.share_token 现在需要改为 share_token=share_token

**Comment by chenlip** [comment]
没有密码也需要传这个参数吗?

**Comment by lemisky** [comment]
对，需要的，这是访问 token，而不管有没有密码，有没有密码的区别在于 获取 token 的时候

**Comment by chenlip** [comment]
ok, 我试了一下, 成了;

**Comment by chenlip** [comment]
太谢谢了, 我花了一个小时试这个函数

**Comment by lemisky** [comment]
哈哈哈

**Comment by lemisky** [comment]
好的
