### ISSUE TITLE
文件夹同步，上传，下载 api 增加功能

### ISSUE THREAD

**Issue by tensor-tech** [foyoux/aligo#42]
**新功能请求**

- 文件夹同步api 应该添加是否允许删除
- 上传api 添加 进度 回调函数
- 下载api 添加 进度回调函数

**Comment by lemisky** [comment]
回调函数能说清楚点吗？不知道需要怎么写

**Comment by tensor-tech** [comment]
> 回调函数能说清楚点吗？不知道需要怎么写
.upload_file(file_path, folder_id, *, callback, uploaded_handler)
<html>
<body>


callback | func | 进度回调函数 | N | 默认None
-- | -- | -- | -- | --
uploaded_handler | func | 上传回调函数 | N | 默认None


</body>
</html>
<html>
<body>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">进度回调函数: 该函数用于跟踪上传进度<br style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">show_progress(file_name, total_size, now_size)</code></p>

参数 | 类型 | 说明
-- | -- | --
file_name | str | 上传文件名
total_size | int | 文件总字节数
now_size | int | 已上传字节数

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">示例:</p><div class="snippet-clipboard-content notranslate position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: auto !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre lang="pydocstring" class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; margin-top: 0px; margin-bottom: 16px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; background-color: var(--color-canvas-subtle); border-radius: 6px;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0px; margin: 0px; background: transparent; border-radius: 6px; word-break: normal; white-space: pre; border: 0px; display: inline; overflow: visible; line-height: inherit; overflow-wrap: normal;">&gt;&gt;&gt; def show_progress(file_name, total_size, now_size):
...     """显示进度的回调函数"""
...     percent = now_size / total_size
...     bar_len = 40  # 进度条长总度
...     bar_str = '&gt;' * round(bar_len * percent) + '=' * round(bar_len * (1 - percent))
...     print('\r{:.2f}%\t[{}] {:.1f}/{:.1f}MB | {} '.format(
...         percent * 100, bar_str, now_size / 1048576, total_size / 1048576, file_name), end='')
...     if total_size == now_size:
...         print('')  # 下载完成换行

&gt;&gt;&gt; def handler(fid, is_file):
        if is_file:
            lzy.set_desc(fid, '这是文件的描述', is_file=True)

&gt;&gt;&gt; code= lzy.upload_file(r"D:\zaxtyson\Softwares\ChromeSetup.exe", -1, callback=show_progress, uploaded_handler=handler)
100.00%	[&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;] 1.1/1.1MB | ChromeSetup.exe 

&gt;&gt;&gt; code == LanZouCloud.SUCCESS
True</code></pre></div>
</body>
</html>

**Comment by tensor-tech** [comment]
> , uploaded

**Comment by tensor-tech** [comment]
https://github.com/zaxtyson/LanZouCloud-API/wiki/0x06-%E4%B8%8A%E4%BC%A0%E5%92%8C%E4%B8%8B%E8%BD%BD#upload_filefile_path-folder_id--callback-uploaded_handler

**Comment by lemisky** [comment]
好的，抽空搞搞

**Comment by lemisky** [comment]
只需要单个文件进度，对吗？不管是上传单个文件，还是上传文件夹

**Comment by tensor-tech** [comment]
> 
单个 文件进度。

**Comment by lemisky** [comment]
好

**Comment by lemisky** [comment]
考虑了下，没有轻易添加此特性，这个需求可能并不常用，此 issue 先挂起，如果有其他网友有相同或类似需求，我会考虑添加。

你暂时可以 “曲线救国” 通过 log handler 来实现

**Comment by lemisky** [comment]
再次感谢 你的 反馈 :rose:

**Comment by tensor-tech** [comment]
暂时 曲线救国
