### ISSUE TITLE
sync_folder的参数file_filter，说明和实际不符

### ISSUE THREAD

**Issue by shi1035** [foyoux/aligo#43]
**错误描述**

sync_folder的参数file_filter，说明中写的“文件过滤函数，参数为 文件绝对路径，返回值为 `True` 则过滤，可用于实现 只同步 特定文件 或 排除某些文件”。
事实上，参数为文件名。

**Comment by lemisky** [comment]
感谢反馈，我去看看

**Comment by lemisky** [comment]
已处理
