### ISSUE TITLE
拉取阿里云盘相册

### ISSUE THREAD

**Issue by zhulianmei** [foyoux/aligo#45]
**新功能请求**

阿里云盘相册在执行 ali.get_file_list()无法获取。是不是可以加上相册的功能

**Comment by lemisky** [comment]
收到收到，周末处理。

**Comment by lemisky** [comment]
已实现相册相关接口，示例：https://github.com/foyoux/aligo/blob/main/examples/example-14%20%E7%9B%B8%E5%86%8C%E7%9B%B8%E5%85%B3API.py

**Comment by zhulianmei** [comment]
666，神速！
