### ISSUE TITLE
pycharm出来的二维码，使用云盘扫描不成功

### ISSUE THREAD

**Issue by bluescorpio** [foyoux/aligo#5]
pycharm出来的二维码，使用云盘扫描不成功
参考代码是入门版的：
from aligo import Aligo

ali = Aligo()

# 获取用户信息
user = ali.get_user()

# 获取网盘根目录文件列表
ll = ali.get_file_list()
print(ll)

**Comment by lemisky** [comment]
- 在类Unix中， 为了兼容纯控制台环境， 默认显示登录二维码的方式是直接打印在控制台中
- 扫描二维码不成功， 一般是二维码显示不完全， 你可以自定义二维码显示方式， 可以参考 [这里](https://github.com/foyoux/aligo/wiki/%E7%99%BB%E5%BD%95#%E8%A1%A5%E5%85%85%E8%AF%B4%E6%98%8E) 
- 使用 `refresh_token` 登录也是可以的， 参考 [这里](https://github.com/foyoux/aligo/wiki/%E7%99%BB%E5%BD%95#refresh_token)， 同时要注意 [这里](https://github.com/foyoux/aligo/releases/tag/v1.3.0)
