### ISSUE TITLE
添加一个快捷加密

### ISSUE THREAD

**Issue by hmm-ctrl** [foyoux/aligo#50]
有时候阿里云盘会吃文件，建议加一个加密模式，仍然能正常操作，但是最终上传的时候只会上传一个加密的压缩文件，所有的文件和文件夹操作都是在这个压缩包中进行的，当然还可以试着再做个快速迁移，把整个云盘里的东西都搬到压缩包里（然后删除原文件？），如果能指定压缩包格式的话更好，谢谢了

**Comment by lemisky** [comment]
感谢反馈 ❤️ 

什么情况下会吃文件，我并太清楚，因为没需求，并没深入研究。这个需求在 库 的外部做更合适，因为似乎并不是它的职责。

如果有完美方案，是多数用户需求，我会考虑添加。

**Comment by dark-origin** [comment]
建议使用cryptomatory
