### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by hmm-ctrl** [foyoux/aligo#51]
1.建议将 `download_file` `download_files` `download_folder`
`upload_file` `upload_files` `upload_folder`
合并为`download`和`upload`
同时允许直接传递获取的文件/文件夹对象或文件路径
2.建议后台增加一个字典形式的网盘文件目录缓存来减轻压力（可能会比直接遍历快一点？）

**Comment by lemisky** [comment]
感谢你的建议 🌹 🌹 🌹 

download_xxx 相关方法，下次更新一并考虑

缓存数据这个，最初是做了的，但是会带来一些问题，导致新手疑惑。最主要的原因是无法及时响应，例如 在其他端对文件修改了，就会产生误差。本端删除文件缓存也无法得到体现（当然是可以维护的，但是麻烦，多半也会出 BUG），没有完美方案，暂不考虑。

如果希望缓存提高速度，可以自行存放。

再次感谢你的反馈 🌹 


----

另外一方面原因是，自己懒🤣

**Comment by lemisky** [comment]
我想起来了，下载之所以区分 download_file 和 download_folder，是考虑到效率原因，这样每次调一次这个方法要增加一个请求，下载100个，可能就多出100个请求，对于这种第三方接口，要尽可能减少请求次数，所以当时这么设计的。

对于你说的，下载同时支持文件对象，目前是可以的。
