### ISSUE TITLE
入群二维码过期了

### ISSUE THREAD

**Issue by 931556797** [foyoux/aligo#52]
**新功能请求**

。。。

**Comment by lemisky** [comment]
晚上处理

**Comment by 931556797** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月20日(星期四) 下午4:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [foyoux/aligo] 入群二维码过期了 (Issue #52)





 
晚上处理

**Comment by Sahala08** [comment]
> 好的，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年10月20日(星期四) 下午4:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [foyoux/aligo] 入群二维码过期了 (Issue #52) 晚上处理 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

求更新
