### ISSUE TITLE
BUG: Package requests share_token not converted to str

### ISSUE THREAD

**Issue by JingMatrix** [foyoux/aligo#55]
**操作系统信息**
Linux localhost 5.10.107-android13-4-00004-gf0fe4f768061-ab8935229 on Termux

**错误描述**
With python 11, `share_token` in the `POST` header is not converted to type `str` and thus cause a type error.

**Comment by lemisky** [comment]
调用代码贴来看看，估计是你用错了。

首先更新到最新版

get_share_token 的返回结果直接用就可以了

**Comment by JingMatrix** [comment]
调用方法没有错的，因为在 `python10` 上可以运行。
我使用的是最新版。

这是源代码:
https://github.com/JingMatrix/Alibrary/blob/f7a18c5d306ec3f9455656b312b8a929cb82027f/aliyun-share#L89-L94

为了解决 `python 3.11` 的问题， 我加了一个新的分支：
https://github.com/JingMatrix/Alibrary/blob/0889003a2cd577a80c7dbf656810cf2fccf9ea7f/aliyun-share#L89-L94

**Comment by lemisky** [comment]
share_token = ali.get_share_token(share_id).share_token

改成这样

    share_token = ali.get_share_token(share_id)

**Comment by JingMatrix** [comment]
我原来的代码就是你希望我改成的样子。

我加上 `.share_token` 是因为不加的话在 `python 3.11` 上会报错。

**Comment by lemisky** [comment]
OK，谢谢反馈，抽空处理👏

**Comment by JingMatrix** [comment]
我知道问题所在了，不是 python 版本问题，而是 request 包更新后，就不会自动将对象转为字符串了

**Comment by lemisky** [comment]
get

**Comment by lemisky** [comment]
那这属于 “aligo” 的问题吗？

`requests` 最新版本是 六月底发布的，到现在已经四个多月没有更新了，应该不存在你说的那种情况。

**Comment by JingMatrix** [comment]
这样的话，那可能大家安装 aligo 的时候在六月前吧。
你更新自己的 request 包，应该就能够遇到这个 bug 了。

**Comment by lemisky** [comment]
能贴下代码吗，我现在试试

**Comment by JingMatrix** [comment]
```python3
from aligo import Aligo

ali = Aligo()
# test https://www.aliyundrive.com/s/8vpM56UhZKW/folder/618774f7cd5b35a4ed874a80bb830404b44de4cd
share_id = '8vpM56UhZKW'
file_id = '618774f7cd5b35a4ed874a80bb830404b44de4cd'
share_token = ali.get_share_token(share_id=share_id)
ali.get_share_file(share_id=share_id,
                   file_id=file_id,
                   share_token=share_token)
```

**Comment by lemisky** [comment]
好的

**Comment by lemisky** [comment]
感谢反馈

**Comment by lemisky** [comment]
> ```python
> from aligo import Aligo
> 
> ali = Aligo()
> # test https://www.aliyundrive.com/s/8vpM56UhZKW/folder/618774f7cd5b35a4ed874a80bb830404b44de4cd
> share_id = '8vpM56UhZKW'
> file_id = '618774f7cd5b35a4ed874a80bb830404b44de4cd'
> share_token = ali.get_share_token(share_id=share_id)
> ali.get_share_file(share_id=share_id,
>                    file_id=file_id,
>                    share_token=share_token)
> ```

确实存在这个问题，requests 6月29 的升级加强了 header 验证

https://github.com/psf/requests/commit/e36f34597ca96c40dbb81d63a8fe9ac0860b8dc3#diff-b4b6ac4e508ec3e142b8b8a3cf33b9ab925e3bdd03dbbe859384760746b1ac76R1027

**Comment by lemisky** [comment]
@JingMatrix 你的分析很有道理 :+1:
