### ISSUE TITLE
下载子文件夹失败

### ISSUE THREAD

**Issue by HalvesChen** [foyoux/aligo#59]
**操作系统信息**
ubuntu 
python 3.6

**错误描述**
通过download_folder, file_id下载子文件夹失败，命令只是创建了文件夹，没有下载文件
部分代码如下：
```
file = ali.get_file_by_path('./scannetv2')
ali.download_folder(file.file_id, local_folder='./traindata')
```

**Comment by lemisky** [comment]
aligo 不支持 python 3.6，最低 3.7
![python version](https://img.shields.io/pypi/pyversions/aligo)

**Comment by chendaozai** [comment]
> aligo 不支持 python 3.6，最低 3.7 ![python version](https://camo.githubusercontent.com/f68d88c91475ed1f79db93731b11f52da6fc6d807fa520cbd6ce8744cc77d722/68747470733a2f2f696d672e736869656c64732e696f2f707970692f707976657273696f6e732f616c69676f)

还是不行，代码部分有问题吗？我可以正常打印上面的变量```file```

**Comment by chendaozai** [comment]
> 你试试这样
> 
> ```python
> file = ali.get_folder_by_path('scannetv2')
> ali.download_folder(file.file_id, local_folder='./traindata')
> ```

sry，我上面的文件路径写错了（我运行的路径没错，只是issue里面写错了），代码如下：
```
from aligo import Aligo
ali = Aligo()
file=ali.get_file_by_path('scannet/traindata')
ali.download_folder(file.file_id, local_folder='.')
```
file可以正常打印出```file_id```和```parent_file_id```等信息，但还是没法下载，命令运行后只创建了文件夹

**Comment by lemisky** [comment]
那就是 'scannet/traindata' 里面没有文件

**Comment by lemisky** [comment]
程序有报错吗

**Comment by lemisky** [comment]
你看看 `file.type` 是不是 **folder**

**Comment by chendaozai** [comment]
> 你看看 `file.type` 是不是 **folder**

ok，解决问题了 :)
我自己的路径搞错了，他这个还是能够get到file我还以为我路径没问题
感谢回复哈
