### ISSUE TITLE
大家都在用阿里云盘干什么呢？

### ISSUE THREAD

**Issue by lemisky** [foyoux/aligo#65]
## 欢迎大家留言讨论

**Comment by xcsweb** [comment]
搭建自己的家庭影音库

**Comment by Thesoul20** [comment]
当作自建NAS的备分盘。将重要的文件进行二次备份

**Comment by Thesoul20** [comment]
> 当作自建NAS的备分盘。将重要的文件进行二次备份

我用aligo 写了一个文件夹同步的Docker镜像：[thesoul24/aligo_sync_folder](https://hub.docker.com/r/thesoul24/aligo_sync_folder)
- [x] 不同本地文件可以相隔不同时间将文件夹中的内容同步
- [x] 端口扫码登陆
- [x] 异步架构

**Comment by li1234yun** [comment]
文件备份
