### ISSUE TITLE
如何退出aligo实例

### ISSUE THREAD

**Issue by Biubush** [foyoux/aligo#68]
创建完一个aligo对象后，如何退出登录销毁这个对象，使用del发现只能删除引用不能回收实例，官方wiki里没找到方法，故来求作者大大指点一二。

**Comment by lemisky** [comment]
hello hello

**Comment by lemisky** [comment]
python 里如何一个对象使用了，会自动回收的，不知道你怎么 确定 del 后没有被回收的

**Comment by lemisky** [comment]
你也可以主动调用，参考 gc 模块 https://docs.python.org/zh-cn/3/library/gc.html#module-gc

**Comment by Biubush** [comment]
> 你也可以主动调用，参考 gc 模块 https://docs.python.org/zh-cn/3/library/gc.html#module-gc

非常感谢，问题已解决❥(^_-)
