### ISSUE TITLE
get_file_by_path()问题

### ISSUE THREAD

**Issue by karhow** [foyoux/aligo#70]
**操作系统信息**

。。。
# 云盘目录
        remote_folder = ali.get_file_by_path(path=remote_path)
        # assert isinstance(remote_folder, ali.BaseFile)
        logger.info('获取到云端目录：{}'.format(remote_folder))
        # 上传至网盘
        ali.upload_file(f'{retval}/{files_name}', remote_folder=remote_folder.file_id)

**错误描述**
aligo.INFO 获取到云端目录：None

ali.upload_file(f'{retval}/{files_name}', remote_folder=remote_folder.file_id)
AttributeError: 'NoneType' object has no attribute 'file_id'

。。。

get_file_by_path方法返回Node 不再能获取到file id了

**Comment by karhow** [comment]
@[lemisky](https://github.com/lemisky)

**Comment by lemisky** [comment]
请使用 get_folder_by_path
