### ISSUE TITLE
建议增加watchdog

### ISSUE THREAD

**Issue by xep007** [foyoux/aligo#71]
**新功能请求**

①这是我用过的最好的阿里云盘同步软件。做为同步文件夹使用，既快又好，可以将修改过的文件（同名）准确地上传到云盘备份。
②建议增加python watchdog，用来监视本地同步文件夹，一有变化，触动上传到网盘备份文件夹。这样可以弄成后台进程，不用每次都要上传比对耗时耗流量。

**Comment by lemisky** [comment]
收到收到

**Comment by lemisky** [comment]
我好懒呀😂

**Comment by xep007** [comment]
大大好，首先，您能开源自己的软件，造福我们，已经非常伟大了。况且时值春节，休息一下也是人之常情。没事，慢慢来，等您啥时有空再做，不用急于一时。再次感谢！
另：中午同步未能成功，就该是源文件做了改进吧。提示如下：

***@***.*** ~/bin]$ python aligo-sync.py
/usr/lib/python3.10/site-packages/requests/__init__.py:102:
RequestsDependencyWarning: urllib3 (1.26.12) or chardet
(5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({})
doesn't match a supported "
14:36:02.133 aligo.INFO Config /home/xep008/.aligo/aligo.json
14:36:02.133 aligo.INFO 日志等级 DEBUG

14:36:02.371 aligo.INFO 类 Unix 操作系统
14:36:02.371 aligo.INFO 加载配置文件 /home/xep008/.aligo/aligo.json
14:36:02.584 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
401 84
14:36:02.584 aligo.INFO 刷新 token
14:36:02.670 aligo.INFO POST https://api.aliyundrive.com/v2/account/token
200 1853
14:36:02.671 aligo.INFO 刷新 token 成功
14:36:02.671 aligo.INFO 保存配置文件 /home/xep008/.aligo/aligo.json
14:36:02.770 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
200 4748
14:36:02.773 aligo.INFO sync_folder: 双端同步
14:36:02.870 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
200 11172
14:36:02.973 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
200 4893
14:36:02.974 aligo.DEBUG 文件 2020年安溪县各级教学名师、学科带头人、骨干教师考核情况汇总表（安溪一中）.xlsx
已存在，且sha1值相同，跳过
14:36:03.067 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
200 707
14:36:04.247 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
200 7214
14:36:04.248 aligo.DEBUG 文件 2019-2020上学期.org <http://xn--fhqp93ai7i.org>~
已存在，且sha1值相同，跳过
14:36:04.358 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
200 13043
14:36:04.360 aligo.DEBUG 文件 2019-2020上学期.org_archive 已存在，且sha1值相同，跳过
14:36:04.360 aligo.DEBUG 文件 2019-2020上学期.org <http://xn--fhqp93ai7i.org>
已存在，且sha1值相同，跳过
14:36:04.360 aligo.DEBUG 文件 2018-2019上学期.org <http://xn--fhqp93ai7i.org>
已存在，且sha1值相同，跳过
14:36:04.361 aligo.DEBUG 文件 2018-2019下学期.org <http://xn--ghq883ai7i.org>
已存在，且sha1值相同，跳过
14:36:04.361 aligo.DEBUG 文件 教务处文件.org <http://xn--5nq32gf6g09nwga.org>
已存在，且sha1值相同，跳过
14:36:07.415 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
504 15
14:36:07.415 aligo.WARNING 504 Gateway Timeout
Traceback (most recent call last):
  File "/home/xep008/bin/aligo-sync.py", line 15, in <module>
    ali.sync_folder('/home/xep008/MEGA', obj_remote_folder.file_id)
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 75, in sync_folder
    self.__sync_folder(local_folder, remote_folder, flag, file_filter,
ignore_content, follow_delete, drive_id)
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 108, in __sync_folder
    self.__sync_all(
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 144, in __sync_all
    self.__sync_folder(local_file, remote_file.file_id, flag, file_filter,
ignore_content, follow_delete,
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 101, in __sync_folder
    remote_file = f.name
AttributeError: 'Null' object has no attribute 'name'

foyou ***@***.***> 于2023年2月4日周六 12:12写道：

**Comment by lemisky** [comment]
新年好

**Comment by lemisky** [comment]
你今天升级了吗，

这个应该是阿里云盘服务的问题，不过我可以改进下代码兼容一下

**Comment by lemisky** [comment]
已处理

**Comment by xep007** [comment]
我升级了aligo,当场再同步一下。同步时间较长，还未结束，应该没问题。若有什么发现，再向您提。
感谢大大！

foyou ***@***.***> 于2023年2月4日周六 15:20写道：

**Comment by xep007** [comment]
大大好，刚升级到5.5.10版本，进行同步升级时提示以下信息：

17:06:58.614 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list
502 11
17:06:58.614 aligo.WARNING 502 Bad Gateway
Traceback (most recent call last):
  File "/home/xep008/bin/aligo-sync.py", line 15, in <module>
    ali.sync_folder('/home/xep008/MEGA', obj_remote_folder.file_id)
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 75, in sync_folder
    self.__sync_folder(local_folder, remote_folder, flag, file_filter,
ignore_content, follow_delete, drive_id)
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 108, in __sync_folder
    self.__sync_all(
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 144, in __sync_all
    self.__sync_folder(local_file, remote_file.file_id, flag, file_filter,
ignore_content, follow_delete,
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 108, in __sync_folder
    self.__sync_all(
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 144, in __sync_all
    self.__sync_folder(local_file, remote_file.file_id, flag, file_filter,
ignore_content, follow_delete,
  File
"/home/xep008/.local/lib/python3.10/site-packages/aligo/apis/SyncFolder.py",
line 101, in __sync_folder
    remote_file = f.name
AttributeError: 'Null' object has no attribute 'name'

foyou ***@***.***> 于2023年2月4日周六 15:20写道：

**Comment by lemisky** [comment]
已处理
