### ISSUE TITLE
增加参数，设置后在refresh_token失效时不自动进行二维码login

### ISSUE THREAD

**Issue by karma-sun** [foyoux/aligo#73]
增加参数，设置后在refresh_token失效时不自动进行二维码login
因为在background模式的服务程序中使用，二维码login会卡住程序

**Comment by lemisky** [comment]
已处理

**Comment by lemisky** [comment]
增加 re_login 参数，默认 True，表示刷新 token 失败后继续（等待）登录，设为 False 则可达到目的
