### ISSUE TITLE
看了一下源码，好像没有签到相关的，可否添加相关接口？

### ISSUE THREAD

**Issue by black-zero358** [foyoux/aligo#75]
**新功能请求**
签到相关接口
。。。

**Comment by lemisky** [comment]
咋啦

**Comment by lemisky** [comment]
参考 https://github.com/foyoux/aligo/blob/main/examples/example-21%20%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%88%B0.py

我不太确定有效，无效的反馈，这家伙要验证，得再等一天

**Comment by black-zero358** [comment]
> 参考 https://github.com/foyoux/aligo/blob/main/examples/example-21%20%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%88%B0.py
> 
> 我不太确定有效，无效的话反馈，这家伙要验证，得再等一天

我只在翻了翻源码，没仔细看例子就开issue了
刚刚看到了，就把issue关了
![19E3B396](https://user-images.githubusercontent.com/53086059/216808970-a3be8015-3a0c-45c0-a6d4-8c04a7bb5013.png)
我的号今天签到了，我找别人试试看有没有用
