### ISSUE TITLE
能否对sync_folder添加多线程支持以加速上传速度 

### ISSUE THREAD

**Issue by somewheve** [foyoux/aligo#79]
**新功能请求**

能否对sync_folder函数添加多线程支持以加速上传速度 

大部分时间都在等待IO 这是相当不节省时间的。 

https://github.com/foyoux/aligo/blob/bcb64b90a47ddd3b7d3d13854ebe6b4cea2ca4d9/aligo/apis/SyncFolder.py#L89

**Comment by lemisky** [comment]
😂😂有点懒，欢迎贡献代码

还有文件监控的😂

**Comment by somewheve** [comment]
等我忙完这阵子把 要到 3月份才行
