### ISSUE TITLE
获取文件出现 UserDeviceOffline错误，刚开始还是正常的，重新获取token后，错误依然存在

### ISSUE THREAD

**Issue by liangyunli** [foyoux/aligo#86]
**操作系统信息**

python3.9
。。。

**错误描述**
21:10:31.723 aligo.INFO 日志等级 DEBUG
21:10:31.723 aligo.INFO MacOS 操作系统
21:10:31.723 aligo.INFO 加载配置文件 /Users/lyl/.aligo/aligo.json
21:10:31.724 aligo.INFO 保存配置文件 /Users/lyl/.aligo/aligo.json
21:10:31.971 aligo.INFO POST https://api.aliyundrive.com/v2/file/get 401 100
21:10:32.046 aligo.INFO POST https://api.aliyundrive.com/users/v1/users/device/create_session 200 58
21:10:32.099 aligo.INFO POST https://api.aliyundrive.com/v2/file/get 401 100
21:10:32.165 aligo.INFO POST https://api.aliyundrive.com/users/v1/users/device/create_session 200 58
21:10:32.217 aligo.INFO POST https://api.aliyundrive.com/v2/file/get 401 100
21:10:32.294 aligo.INFO POST https://api.aliyundrive.com/users/v1/users/device/create_session 200 58
21:10:32.347 aligo.INFO POST https://api.aliyundrive.com/v2/file/get 401 100
21:10:32.424 aligo.INFO POST https://api.aliyundrive.com/users/v1/users/device/create_session 200 58
21:10:32.477 aligo.INFO POST https://api.aliyundrive.com/v2/file/get 401 100
21:10:32.555 aligo.INFO POST https://api.aliyundrive.com/users/v1/users/device/create_session 200 58
21:10:32.555 aligo.INFO 重试 5 次仍旧失败
21:10:32.555 aligo.WARNING [method status_code] POST 401
21:10:32.555 aligo.WARNING [url] https://api.aliyundrive.com/v2/file/get
21:10:32.555 aligo.WARNING [response body] {"code":"UserDeviceOffline","message":"Device offline","requestId":"0a0070ad16770714325206921e3a63"}

  File "/Users/lyl/Library/Python/3.9/lib/python/site-packages/aligo/apis/File.py", line 57, in get_file
    return self._core_get_file(body)
  File "/Users/lyl/Library/Python/3.9/lib/python/site-packages/aligo/core/BaseAligo.py", line 194, in _core_get_file
    response = self._post(V2_FILE_GET, body=body)
  File "/Users/lyl/Library/Python/3.9/lib/python/site-packages/aligo/core/BaseAligo.py", line 105, in _post
    return self._auth.post(path=path, host=host, body=body, headers=headers, ignore_auth=ignore_auth)
  File "/Users/lyl/Library/Python/3.9/lib/python/site-packages/aligo/core/Auth.py", line 436, in post
    return self.request(method='POST', url=host + path, params=params,
  File "/Users/lyl/Library/Python/3.9/lib/python/site-packages/aligo/core/Auth.py", line 423, in request
    self.error_log_exit(response)
  File "/Users/lyl/Library/Python/3.9/lib/python/site-packages/aligo/core/Auth.py", line 73, in error_log_exit
    raise AligoFatalError(response.text)
aligo.error.AligoFatalError: {"code":"UserDeviceOffline","message":"Device offline","requestId":"0a0070ad16770714325206921e3a63"}
。。。

**Comment by liangyunli** [comment]
网页同一个token,功能正常

**Comment by lemisky** [comment]
aligo.__version__ 看下版本

**Comment by liangyunli** [comment]
aligo              5.5.17

**Comment by liangyunli** [comment]
升级到 5.5.20 错误还是存在

**Comment by lemisky** [comment]
最新版本 5.5.20

**Comment by liangyunli** [comment]
升级了，异常还在

**Comment by lemisky** [comment]
如果你用的浏览器上面的token，那你需要替换一下 x-device-id，在对应的配置文件中，替换的 要符合浏览器上面的id格式

**Comment by lemisky** [comment]
你可以将浏览器上面的x-device-id换上去

**Comment by liangyunli** [comment]
好的，谢谢

**Comment by liangyunli** [comment]
扫码登录也是失败，应该是设备上限了，每次启动aligo,都会占用一个设备？
https://www.aliyundrive.com/s/uhvthBtw2AZ

**Comment by lemisky** [comment]
换个id就会占一个设备

**Comment by lemisky** [comment]
还是报错吗，不应该呀。

**Comment by liangyunli** [comment]
我的设备上限了，之前的全下线了，应该就好了，被aligo占用了六七个

**Comment by lemisky** [comment]
OK，那所以之前的问题也可能是这个原因

**Comment by liangyunli** [comment]
现在有个问题是，脚本每次启动，都算占用一个设备，很快就占满10个了，就出现上面的问题了

**Comment by liangyunli** [comment]
现在有个问题是，脚本每次启动，都算占用一个设备，很快就占满10个了，就出现上面的问题了

**Comment by liangyunli** [comment]
有个小问题，不知道算不算bug,脚本初始化时，只要传refresh_token，都会占用一个设备，即使是之前已经用同一个token初始化的情况下

**Comment by lemisky** [comment]
收到收到，我明天去看下

**Comment by liangyunli** [comment]
好的，可以在app内设置->账号与安全->登录设备管理   查看已经登录的设备
