### ISSUE TITLE
get_share_file_list 出现了问题

### ISSUE THREAD

**Issue by zok2** [foyoux/aligo#89]
**操作系统信息**

mac os

**错误描述**

example-16 导出分享中所有文件信息.py
example-17 保存分享中所有文件.py
出现了错

23:02:43.729 aligo.INFO Config /Users/zok2/.aligo/aligo.json
23:02:43.729 aligo.INFO 日志等级 DEBUG
23:02:43.729 aligo.INFO MacOS 操作系统
23:02:43.729 aligo.INFO 加载配置文件 /Users/zok2/.aligo/aligo.json
23:02:43.730 aligo.INFO 保存配置文件 /Users/zok2/.aligo/aligo.json
23:02:43.820 aligo.INFO POST https://api.aliyundrive.com/v2/share_link/get_share_token 200 560
Traceback (most recent call last):
  File "/Users/zok2/code/python/aligo/src/aligo/examples/example-17 保存分享中所有文件.py", line 10, in <module>
    ali.share_file_save_all_to_drive(share_id, share_token)
  File "/Users/zok2/code/python/aligo/src/aligo/apis/Share.py", line 577, in share_file_save_all_to_drive
    file_list = self.get_share_file_list(share_token, parent_file_id=parent_file_id)
  File "/Users/zok2/code/python/aligo/src/aligo/apis/Share.py", line 266, in get_share_file_list
    body = GetShareFileListRequest(share_id=share_token.share_id, parent_file_id=parent_file_id, **kwargs)
AttributeError: 'str' object has no attribute 'share_id'
Process finished with exit code 1

。。。
<img width="975" alt="image" src="https://user-images.githubusercontent.com/42925731/221599447-595db823-3c9c-4555-9c18-9d035569f540.png">

**Comment by lemisky** [comment]
例子过期了，明早处理

**Comment by zok2** [comment]
感谢

**Comment by lemisky** [comment]
已处理
