### ISSUE TITLE
可选择的下载文件夹的子文件

### ISSUE THREAD

**Issue by chendaozai** [foyoux/aligo#91]
**新功能请求**

能不能加一个参数用来判断文件夹下的文件是否上传或者下载？判断的依据可以用文件名

**Comment by lemisky** [comment]
你的意思是 不递归下载吗？

**Comment by chendaozai** [comment]
可能我没表述清楚。在下载文件夹时，目前的api是会逐个下载文件夹下的所有文件。我希望的是可以通过传入一个参数，用来判断该文件夹下的子文件是否是我要下载的。例如我只想下载`./dataset/`下的`*.pth`文件，那么在调用下载函数的时候额外传入参数‘*.pth’就好了。

**Comment by lemisky** [comment]
明白了，已安排，请更新

**Comment by chendaozai** [comment]
感谢 :)
