### ISSUE TITLE
下载文件夹时获取的url为空

### ISSUE THREAD

**Issue by GOT-youze** [foyoux/aligo#95]
**操作系统信息**
win11
。。。

**错误描述**
ali.download_folder(folder_file_id=file.file_id, local_folder=local_folder)
报错：下载失败: 获取的url为空, 文件可能被屏蔽导致无法下载
怎么解决
。。。

**Comment by lemisky** [comment]
更新版本

**Comment by GOT-youze** [comment]
收到
